### Cadastro de Usuário
POST http://localhost:3000/login
Content-Type: application/json

{
  "login": "marcos@email.com",
  "password": "Senha12345"
}

### "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik1hcmNvcyBTaWx2YSIsImlhdCI6MTc3MTEyNTg1MCwiZXhwIjoxNzczNzE3ODUwfQ.isu4Qqpd4Ka0LBTp5e9wF9MmHdblVWcLtR6f-kmvz9E"

GET http://localhost:3000/tasks/daily
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik1hcmNvcyBTaWx2YSIsImlhdCI6MTc3MTEyNTg1MCwiZXhwIjoxNzczNzE3ODUwfQ.isu4Qqpd4Ka0LBTp5e9wF9MmHdblVWcLtR6f-kmvz9E


GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik1hcmNvcyBTaWx2YSIsImlhdCI6MTc3MTEyNTg1MCwiZXhwIjoxNzczNzE3ODUwfQ.isu4Qqpd4Ka0LBTp5e9wF9MmHdblVWcLtR6f-kmvz9E