FROM node:20-alpine

WORKDIR /frontend

COPY package*.json ./

RUN npm config set fetch-retry-maxtimeout 120000
RUN npm config set fetch-retries 5

RUN npm install

COPY . .

EXPOSE 4200

CMD ["npm", "start"]  